### ISSUE TITLE
[bugs] node js app not work with link

### ISSUE THREAD

**Issue by AIvanovitch** [MwSpaceLLC/LaraveX#1]
Package bust be fixed with php.conf | html.conf and backslash for work with node apps.

Browser => `No input file specified. `

**Comment by MwSpaceLLC** [comment]
Very tnks to try this work! 

The issue is passed to dev team, u can try to download fixed package at LaraveX 1.18.5

![image](https://user-images.githubusercontent.com/29952045/83028026-2bfc0600-a031-11ea-9ef1-a8f1b082d1f4.png)

The error is wrong configurator in override method in nginx .def
