### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation: 1055 Expression

### ISSUE THREAD

**Issue by AIvanovitch** [MwSpaceLLC/LaraveX#14]
![image](https://user-images.githubusercontent.com/53446030/101971066-b81cf600-3c2e-11eb-8b7f-79948ed7f25f.png)

**Comment by MwSpaceLLC** [comment]
In laravel with MySql go to file config/database.php and it change in array MySql mode strict to false.

![image](https://user-images.githubusercontent.com/29952045/101971085-dedb2c80-3c2e-11eb-8510-64ad0738297c.png)
