### ISSUE TITLE
cURL error 60: SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by AIvanovitch** [MwSpaceLLC/LaraveX#5]
cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

![image](https://user-images.githubusercontent.com/53446030/85040876-8e0bdf00-b189-11ea-9321-4ec09313efce.png)

**Comment by MwSpaceLLC** [comment]
Thanks for report.

Check new version 1.9.3 | We have insert certificate.pem for root curl local ssl.
