### ISSUE TITLE
Payload Too Large

### ISSUE THREAD

**Issue by AIvanovitch** [MwSpaceLLC/LaraveX#6]
Hi there,

We are under dev, and we have some errors like:
![image](https://user-images.githubusercontent.com/53446030/92610076-9589e280-f2b7-11ea-84c5-bc0382ca7c38.png)

**Comment by MwSpaceLLC** [comment]
Thanks!

U must update php & nginx post size listener:

First, go to your LARAVEX installation: 

![image](https://user-images.githubusercontent.com/29952045/92610202-b8b49200-f2b7-11ea-8368-3b4caac21c1e.png)

Then, change in **php/php.ini.def** your php value, example:

```
post_max_size = 6G
upload_max_filesize = 4G
memory_limit = 8G
```

Now, update NGINX server parameter nginx/conf/nginx.conf example:

```
  client_max_body_size 1024M;
```

Perfect! u must reboot your LARAVEX server to reload new parameter!
