### ISSUE TITLE
VB Runtime missed

### ISSUE THREAD

**Issue by Tlukis** [MwSpaceLLC/LaraveX#7]
Hi. This is portable app but for running this package i have must VB runtimes.
I want running on server but my owner is not allow install anything packages/applications.

My question is: why this app is not contain VB runtimes, or where i can download VB runtimes as portable (dll files only for copy to base dir App)?

Thanks

**Define "Portable":**
complete package able to be easily carried or moved to another PC or device

**Comment by MwSpaceLLC** [comment]
Hi there,

Please, specific server attributes and requirements.

- U have installed *\assets\VC_redist.x64.exe* ?
- Wich error prompt at startup ?
- Have u searched online ?

Please send us more info,

Have a good Day!

**Comment by MwSpaceLLC** [comment]
Close for inactivity

**Comment by Tlukis** [comment]
Please add/extract directly packages to folder.

**Comment by MwSpaceLLC** [comment]
That package is automatically loaded on the first installation so we can't move the content.

The system should automatically install it. If this did not happen you could indicate your development environment so as to replicate the problem.

Thanks, we will investigate this in the future
